In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [4]:
data_listing = pd.read_csv("data/CRMLSListingMaster.csv", low_memory=False)
data_sold = pd.read_csv("data/CRMLSSoldMaster.csv", low_memory=False)

data_listing.head()

,source_file,file_period,sort_date,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName__dup2,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress__dup2
0,CRMLSListing202401.csv,202401,2024-01-01,1399990.0,1043760653,joe@porchlightsocal.com,2024-03-15,1270000.0,Joseph,Vahedi,...,2.0,NaN,2.0,Vista Unified,92083,eXp Realty of Southern CA,252.0,9897.0,NaN,123 Flores Lane
1,CRMLSListing202401.csv,202401,2024-01-01,789900.0,1053093534,kiva@kivakendrick.com,2024-02-26,800000.0,Kiva,Kendrick,...,NaN,False,2.0,Los Angeles Unified,90746,R & R Realty,NaN,5070.0,NaN,19922 Enslow Drive
2,CRMLSListing202401.csv,202401,2024-01-01,1050000.0,1054014526,sarah.pearce@cbrealty.com,NaN,NaN,Sarah,Pearce,...,NaN,False,NaN,NaN,92262,NaN,NaN,10019.0,NaN,2030 E Acacia Road
3,CRMLSListing202401.csv,202401,2024-01-01,1250000.0,1054022382,mricks@mypsrealtor.com,2024-02-26,1199000.0,Michael,Ricks,...,NaN,False,2.0,NaN,92262,BHG Desert Lifestyle Properties,NaN,10454.0,NaN,1695 E Buena Vista Drive
4,CRMLSListing202401.csv,202401,2024-01-01,4750000.0,1054022420,james@larealproperty.com,NaN,NaN,James,Maxwell,...,NaN,False,2.0,NaN,90291,NaN,NaN,3084.0,NaN,2915 S Grand Canal

In [5]:
data_sold.shape, data_listing.shape

((371009, 87), (499306, 87))

In [6]:
def missing_summary(df, df_name="data"):
    missing_count = df.isna().sum()
    missing_pct = df.isna().mean() * 100

    summary = pd.DataFrame({
        "column": df.columns,
        "missing_count": missing_count.values,
        "missing_pct": missing_pct.values
    }).sort_values("missing_pct", ascending=False)

    high_missing = summary[summary["missing_pct"] > 90]

    print(f"\nMissing value summary for {df_name}:")
    display(summary)

    print(f"\nColumns in {df_name} with >90% missing values:")
    display(high_missing)

    return summary, high_missing

In [7]:
listing_missing_summary, listing_high_missing = missing_summary(data_listing, "data_listing")
sold_missing_summary, sold_high_missing = missing_summary(data_sold, "data_sold")

Missing value summary for data_listing:

                          column  missing_count  missing_pct
63                  BusinessType         499306        100.0
67                 CoveredSpaces         499306        100.0
85  MiddleOrJuniorSchoolDistrict         499306        100.0
53                       TaxYear         499306        100.0
31               TaxAnnualAmount         499306        100.0
..                           ...            ...          ...
33            PropertyType__dup2              0          0.0
29             ListingKeyNumeric              0          0.0
34                     MlsStatus              0          0.0
65               ListPrice__dup2              0          0.0
61           ListingContractDate              0          0.0

[87 rows x 3 columns]

Columns in data_listing with >90% missing values:

                          column  missing_count  missing_pct
63                  BusinessType         499306   100.000000
67                 CoveredSpaces         499306   100.000000
85  MiddleOrJuniorSchoolDistrict         499306   100.000000
53                       TaxYear         499306   100.000000
31               TaxAnnualAmount         499306   100.000000
28        AboveGradeFinishedArea         499306   100.000000
26               FireplacesTotal         499306   100.000000
58      ElementarySchoolDistrict         499306   100.000000
62        BelowGradeFinishedArea         496530    99.444028
59         CoBuyerAgentFirstName         485774    97.289838
39                   BuilderName         476018    95.335926
75             LotSizeDimensions         473139    94.759326
54             BuildingAreaTotal         455168    91.160130

Missing value summary for data_sold:

                          column  missing_count  missing_pct
63                  BusinessType         371009        100.0
65                 CoveredSpaces         371009        100.0
80  MiddleOrJuniorSchoolDistrict         371009        100.0
54                       TaxYear         371009        100.0
33               FireplacesTotal         371009        100.0
..                           ...            ...          ...
36             ListingKeyNumeric              0          0.0
24                ListOfficeName              0          0.0
23                  DaysOnMarket              0          0.0
39                CountyOrParish              0          0.0
64               StateOrProvince              0          0.0

[87 rows x 3 columns]

Columns in data_sold with >90% missing values:

                          column  missing_count  missing_pct
63                  BusinessType         371009   100.000000
65                 CoveredSpaces         371009   100.000000
80  MiddleOrJuniorSchoolDistrict         371009   100.000000
54                       TaxYear         371009   100.000000
33               FireplacesTotal         371009   100.000000
38               TaxAnnualAmount         371009   100.000000
35        AboveGradeFinishedArea         371009   100.000000
58      ElementarySchoolDistrict         371009   100.000000
7                   WaterfrontYN         370783    99.939085
62        BelowGradeFinishedArea         368897    99.430742
8                     BasementYN         363720    98.035358
81         OriginatingSystemName         358351    96.588223
82      OriginatingSystemSubName         358351    96.588223
71             LotSizeDimensions         352983    95.141358
44                   BuilderName         352902    95.119525
55             BuildingAreaTotal         345161    93.033053
59         CoBuyerAgentFirstName         337490    90.965448

In [10]:
drop_listing = [
    "BusinessType",
    "CoveredSpaces",
    "MiddleOrJuniorSchoolDistrict",
    "TaxYear",
    "TaxAnnualAmount",
    "AboveGradeFinishedArea",
    "FireplacesTotal",
    "ElementarySchoolDistrict",
    "BelowGradeFinishedArea",
    "CoBuyerAgentFirstName",
    "BuilderName",
    "LotSizeDimensions"
]

drop_sold = [
    "BusinessType",
    "CoveredSpaces",
    "MiddleOrJuniorSchoolDistrict",
    "TaxYear",
    "FireplacesTotal",
    "TaxAnnualAmount",
    "AboveGradeFinishedArea",
    "ElementarySchoolDistrict",
    "WaterfrontYN",
    "BelowGradeFinishedArea",
    "BasementYN",
    "OriginatingSystemName",
    "OriginatingSystemSubName",
    "LotSizeDimensions",
    "BuilderName",
    "CoBuyerAgentFirstName"
]

data_listing_clean = data_listing.drop(columns=drop_listing, errors="ignore")
data_sold_clean = data_sold.drop(columns=drop_sold, errors="ignore")

In [11]:
data_listing_clean.head()

,source_file,file_period,sort_date,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,...,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName__dup2,AssociationFee,LotSizeSquareFeet,UnparsedAddress__dup2
0,CRMLSListing202401.csv,202401,2024-01-01,1399990.0,1043760653,joe@porchlightsocal.com,2024-03-15,1270000.0,Joseph,Vahedi,...,9897.0,2.0,NaN,2.0,Vista Unified,92083,eXp Realty of Southern CA,252.0,9897.0,123 Flores Lane
1,CRMLSListing202401.csv,202401,2024-01-01,789900.0,1053093534,kiva@kivakendrick.com,2024-02-26,800000.0,Kiva,Kendrick,...,5070.0,NaN,False,2.0,Los Angeles Unified,90746,R & R Realty,NaN,5070.0,19922 Enslow Drive
2,CRMLSListing202401.csv,202401,2024-01-01,1050000.0,1054014526,sarah.pearce@cbrealty.com,NaN,NaN,Sarah,Pearce,...,10019.0,NaN,False,NaN,NaN,92262,NaN,NaN,10019.0,2030 E Acacia Road
3,CRMLSListing202401.csv,202401,2024-01-01,1250000.0,1054022382,mricks@mypsrealtor.com,2024-02-26,1199000.0,Michael,Ricks,...,10454.0,NaN,False,2.0,NaN,92262,BHG Desert Lifestyle Properties,NaN,10454.0,1695 E Buena Vista Drive
4,CRMLSListing202401.csv,202401,2024-01-01,4750000.0,1054022420,james@larealproperty.com,NaN,NaN,James,Maxwell,...,3084.0,NaN,False,2.0,NaN,90291,NaN,NaN,3084.0,2915 S Grand Canal

In [12]:
data_sold_clean.head()

,source_file,file_period,sort_date,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,...,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,CRMLSSold202401.csv,202401,2024-01-01,OrangeCounty,OrangeCounty,"Carpet,Tile",False,False,854990.0,1040790377,...,True,2.0,Montebello Unified,90640,236.0,NaN,NaN,NaN,NaN,NaN
1,CRMLSSold202401.csv,202401,2024-01-01,NorthSanDiegoCounty,NorthSanDiegoCounty,"Laminate,Tile",False,False,399000.0,1044747152,...,False,2.0,Antelope Valley Union,93536,0.0,6882.0,NaN,NaN,NaN,NaN
2,CRMLSSold202401.csv,202401,2024-01-01,Southland,Southland,"Carpet,Tile",False,False,549999.0,1045213113,...,False,3.0,Palmdale,93552,0.0,7293.0,NaN,NaN,NaN,NaN
3,CRMLSSold202401.csv,202401,2024-01-01,SanDiego,SanDiego,NaN,True,False,1750000.0,1045523677,...,False,2.0,NaN,92054,695.0,13567.0,NaN,NaN,NaN,NaN
4,CRMLSSold202401.csv,202401,2024-01-01,PacificWest,PacificWest,"Laminate,Tile",False,False,535000.0,1046369026,...,False,2.0,Rialto Unified,92376,0.0,7700.0,NaN,NaN,NaN,NaN